const nodemailer = require('nodemailer');

(async () => {
  try {
    // Create a test account (Ethereal) for SMTP testing
    const testAccount = await nodemailer.createTestAccount();
    console.log('Ethereal test account created: %s', testAccount.user);

    const transporter = nodemailer.createTransport({
      host: testAccount.smtp.host,
      port: testAccount.smtp.port,
      secure: testAccount.smtp.secure,
      auth: {
        user: testAccount.user,
        pass: testAccount.pass
      }
    });

    const info = await transporter.sendMail({
      from: '"Learning Center" <no-reply@example.com>',
      to: testAccount.user, // send to the ethereal inbox
      subject: 'Test message from learningcenterlogin',
      text: 'This is a test message generated by test-email.js',
      html: '<p>This is a <b>test</b> message generated by <code>test-email.js</code></p>'
    });

    console.log('Message sent: %s', info.messageId);
    console.log('Preview URL: %s', nodemailer.getTestMessageUrl(info) || 'N/A');
  } catch (err) {
    console.error('Test send failed:', err);
    process.exitCode = 1;
  }
})();
